'use strict';
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'helper/omniosfiles.py'), 'utf8');
fs.writeFileSync(path.join(root, 'modules_meshcore/omniosfiles-helper.js'), '// Generated by scripts/build-helper.js; edit helper/omniosfiles.py.\nmodule.exports = ' + JSON.stringify(source) + ';\n');
